version: '2'

services:
  aspnetcoreteste:
    image: aspnetcoreteste_v2:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5001:5001"
    environment:
      - REMOTE_DEBUGGING
